Device page HTML
vigetlabs/GroundRules pull request #29
Opened 2017-07-26 18:14 UTC by benjaminmodayil

Hallo. I'm requesting a PR for this good ol' HTML.

I'm planning on separating the device page out to three pages to account for people that might not be able to use Javascript, but Jason is still setting up the routes so I'm just bundling the general structure according to the comp in the index.html file.

I also quickly created the HTML footer. Since Vivian created it recently from what I understand.

2017-07-26 19:12 UTC, mzlock requested changes

2017-07-26 19:12 UTC, mzlock commented on app/views/devices/index.html.erb
> +<%= render 'shared/partials/nav-global.html' %>
not using a layout for including the header?

2017-07-26 19:12 UTC, mzlock commented on app/views/devices/index.html.erb
> +  <%= render 'shared/partials/header-global.html' %>
Is this header actually "global"? Seems to me it's just the header for this page.

2017-07-26 19:12 UTC, mzlock commented on app/views/devices/index.html.erb
> +        <a href="/device-keurig">
which device is the default device?  I'd make one of these just link to this page (`/devices`), that way you're not duplicating 2 templates.

2017-07-26 19:12 UTC, mzlock commented on app/views/devices/index.html.erb
> +          <%= image_tag("illustrations/ill-keurig.svg", :alt => "Keurig") %>
`alt=""` since you have "Keurig" right below this

2017-07-26 19:12 UTC, mzlock commented on app/views/devices/index.html.erb
> +          <h3>Keurig</h3>
why is this an `<h3>`?  It doesn't seem to be a heading at all to me.

2017-07-26 19:12 UTC, mzlock commented on app/views/devices/index.html.erb
> +          <h3>Coffee Maker</h3>
`alt=""` and no `h3`

2017-07-26 19:12 UTC, mzlock commented on app/views/devices/index.html.erb
> +          <h3>French Roast</h3>
`alt=""` and no `h3`

2017-07-26 19:12 UTC, mzlock commented on app/views/devices/index.html.erb
> +          <h3>French Roast</h3>
Instead of making these `h3`s, you should have an `h1` on the page somewhere that is something like "Devices - Keurig"

2017-07-26 19:12 UTC, mzlock commented on app/views/devices/index.html.erb
> +          <h4>Lukewarm coffee chills my soul</h4>
Why is this an `h4`?

Assuming you have a `h1` in `shared/partials/nav-global.html`, there's still no `h2` on this page and the `h3`s on this page aren't really being used as section headers.

2017-07-26 19:12 UTC, mzlock commented on app/views/devices/index.html.erb
> +        <a href="">
Why is this a `<a>`? If it's for opening the section below it, it really should be a `<button>`.

Also, `<a>` with no `href` value is a bit taboo - hurts accessibility

2017-07-26 19:12 UTC, mzlock commented on app/views/devices/index.html.erb
> +      </li>
My recommended mark-up for these:

```
<li>
    <article>
        <header>
            <h3>Lukewarm coffee chills my soul</h3>
            <button aria-controls="problem-solution-1" aria-expanded="false">
                <!-- raw svg of chevron -->
                <span class="screen-reader-only">Expand</span>
            </button>
        </header>
        <div class="problem__solutions" id="problem-solution-1">
              <p>Text here</p>
        </div>
    </article>
</li>
```

2017-07-26 19:12 UTC, mzlock commented on app/views/shared/partials/_footer-global.html.erb
> +  	&copy; Ground Rules 2017. All rights reserved.</small>
Remove the new line here - let your text editor make the text wrap

2017-07-26 19:12 UTC, mzlock commented on app/views/shared/partials/_footer-global.html.erb
> +    <a href="http://www.viget.com"><%= image_tag("vigetLogo.png") %></a>
image tag needs `alt` text.

Also - cut the png this links to smaller.  You don't need an image as big as what you have.

2017-07-26 19:12 UTC, mzlock commented on app/views/devices/index.html.erb
> +      </li>
This is a lot different from what you have, I know. I can walk you through why I did it this way.

2017-07-26 19:27 UTC, benjaminmodayil commented on app/views/devices/index.html.erb
> +<%= render 'shared/partials/nav-global.html' %>
Right now we have a default layout for all our pages as a wrapper with the stylesheet and javascript file. I asked Jason about creating a layout for these separate pages.

2017-07-26 20:26 UTC, ccomp commented on app/views/devices/index.html.erb
> +  <%= render 'shared/partials/header-global.html' %>
this should be above the main class!

2017-07-26 20:27 UTC, ccomp commented on app/views/devices/index.html.erb
> +  <%= render 'shared/partials/header-global.html' %>
@mzlock it will be global after the adjustments I make on the roasts_page branch

2017-07-26 20:28 UTC, ccomp commented on app/views/devices/index.html.erb
> +          <h3>Keurig</h3>
Isn't 'Keurig' the heading for the problem statements below?

2017-07-26 20:29 UTC, ccomp commented on app/views/devices/index.html.erb
> +          <h3>Keurig</h3>
The only other tag I can think of is <p> for this scenario.

2017-07-26 20:31 UTC, ccomp commented on app/views/devices/index.html.erb
> +          <h3>Keurig</h3>
Also this should be an `<h2>` if it is a heading at all.

2017-07-26 20:32 UTC, ccomp commented on app/views/devices/index.html.erb
> +          <h4>Lukewarm coffee chills my soul</h4>
This should be an `<h3>` I think.

2017-07-26 20:43 UTC, ccomp commented on app/views/devices/index.html.erb
> +      </li>
@mzlock Can you please explain why this an `<article>` and not a `<section>`?

2017-07-26 20:44 UTC, ccomp commented on app/views/shared/partials/_footer-global.html.erb
> +    <a href="http://www.viget.com"><%= image_tag("vigetLogo.png") %></a>
Might as well throw out the ruby code altogether!
`<img src = "vigetLogo.png" alt = "">` should suffice.

2017-07-26 20:46 UTC, ccomp commented on app/views/shared/partials/_footer-global.html.erb
> +    <a href="http://www.viget.com"><%= image_tag("vigetLogo.png") %></a>
Due to the nature of the asset pipeline, if this image is in assets/images you should be okay to link it traditionally.

2017-07-26 20:48 UTC, ccomp commented on app/views/devices/index.html.erb
> +          <%= image_tag("illustrations/ill-keurig.svg", :alt => "Keurig") %>
No need to use Ruby here. It's cleaner to do `<img src = "illustrations/ill-keurig.svg" alt = "">` since the asset pipeline will take care of things.

2017-07-26 20:52 UTC, ccomp commented on app/views/devices/index.html.erb
> +          <%= image_tag("illustrations/ill-french-roast.svg", :alt => "French Roast") %>
`<img src = "illustrations/ill-french-roast.svg" alt = "">`

2017-07-26 20:53 UTC, ccomp commented on app/views/devices/index.html.erb
> +          <h3>Coffee Maker</h3>
`<img src = "illustrations/ill-coffee-maker.svg" alt = "">`

2017-07-26 20:57 UTC, ccomp commented on app/views/devices/index.html.erb
> +          <%= image_tag("icon-caret-hover.svg") %>
I suggest setting `<% hover-icon = image_tag("illustrations/icon-caret-hover.svg", :alt => " ") %>` close to the head of the page and then doing a `<%= hover-icon %>` at each of these declarations for the sake of file size.

2017-07-27 12:53 UTC, benjaminmodayil commented on app/views/devices/index.html.erb
> +          <h3>Keurig</h3>
@mzlock I believe this shouldn't be an h3, that was my miscalculation, but I do think it should be an `<h2>` like @ccomp suggested. All of the problem statements come under a specific device. To me it makes sense that we would need a heading here.

2017-07-27 12:55 UTC, benjaminmodayil commented on app/views/devices/index.html.erb
> +          <h3>French Roast</h3>
Something only for a screen reader, correct?

2017-07-27 15:09 UTC, jroodman commented on app/views/devices/index.html.erb
> +<%= render 'shared/partials/nav-global.html' %>
I added some layout changes in the PR: `Added Layout Specific for Landing Page`.

As a quick side note, partials should be rendered in the following format:
<%= render partial: "shared/partials/nav-global" %>

2017-08-03 14:43 UTC, closed without merging