Roasts page HTML changes and more!
vigetlabs/GroundRules pull request #33
Opened 2017-07-26 22:13 UTC by ccomp

Please review my changes!

<ul>
<li>Added HTML and Rails code to roasts/index.html.erb
<ul>
<li>Rails code automatically generates sections for each roast, reducing redundancy in base HTML</li>
<li>Also generates sections for each roast brand</li>
</ul>
</li>
<li>
Adjusted global header to automatically detect which flow it's on and add content depending
</li>
<li>
Added light-slider-bean and dark-slider-bean to images
</li>

2017-07-26 22:22 UTC, ccomp commented on app/views/roasts/index.html.erb
> +  <% roasts.each_with_index do |roast, index| %>
Ben Tinsley helped me with this one

2017-07-26 22:26 UTC, ccomp commented on app/views/roasts/index.html.erb
> +    <div class="slider"><input type="range" value="0" min="0" max="8" step="1" class="slider__range"></div>
@mzlock Do I need a form label for this slider?

2017-07-26 22:50 UTC, mzlock requested changes

2017-07-26 22:50 UTC, mzlock commented on app/views/roasts/index.html.erb
> +<main class = "roasts">
`<main>` should be around the entire page that isn't the global header and footer.

Also - get rid of those spaces on your class attribute: `class="roasts"`

2017-07-26 22:50 UTC, mzlock commented on app/views/roasts/index.html.erb
> +    <div class="slider"><input type="range" value="0" min="0" max="8" step="1" class="slider__range"></div>
your indentation should be 2 spaces, not 4

2017-07-26 22:50 UTC, mzlock commented on app/views/roasts/index.html.erb
> +    <div class="slider"><input type="range" value="0" min="0" max="8" step="1" class="slider__range"></div>
And this input needs a label.

```
<label class="screen-reader-only" for="roast-range">Roast Level: Light to Dark</label>
<input type="range" value="0" min="0" max="8" step="1" class="slider__range" id="roast-range">
```

2017-07-26 22:50 UTC, mzlock commented on app/views/roasts/index.html.erb
> +    <div class="slider"><input type="range" value="0" min="0" max="8" step="1" class="slider__range"></div>
☝️ note the `for` on the label and the `id` on the input

2017-07-26 22:50 UTC, mzlock commented on app/views/roasts/index.html.erb
> +  <% roasts.each_with_index do |roast, index| %>
:+1:

2017-07-26 22:50 UTC, mzlock commented on app/views/roasts/index.html.erb
> +    <section class = "roasts__view" id = "roast<%= index %>">
get  rid of those spaces. `class="roasts__view" id="roast<%= index %>"`

2017-07-26 22:50 UTC, mzlock commented on app/views/roasts/index.html.erb
> +      <p><strong><%= roast.description %></strong></p>
the entire description is supposed to be bold? (Looking at that `<strong>`)

2017-07-26 22:50 UTC, mzlock commented on app/views/roasts/index.html.erb
> +          <div class="brand__wrapper">
Lines 41-43 here I think you want inside the `if`, but before the `roast.roast_brands.each_with_index`.

You only want one "Popular Brands" section per roast, right?  Then the brands loop should be for the brands _inside_ the section.

2017-07-26 22:50 UTC, mzlock commented on app/views/roasts/index.html.erb
> +              <%=image_tag brand.image.thumb('200x200#').url%>
Add spaces to make this a bit easier to read `<%= image_tag brand.image.thumb('200x200#').url %>`

2017-07-26 22:50 UTC, mzlock commented on app/views/roasts/index.html.erb
> +        </section>
1. you are missing a closing `</div>` here

2. If you move lines 37-39 outside of the brands loop, then the closing tags for those lines also need to be moved outside of the loop (after the `<% end %>` on the next line)

2017-07-26 22:50 UTC, mzlock commented on app/views/layouts/application.html.erb
> +<% url_path = request.fullpath.split("/") %>
Still need this here since you're using it in the global nav file?

2017-07-26 22:50 UTC, mzlock commented on app/views/shared/partials/_header-global.html.erb
>  </header>
Watch indentation in this file!  I think you have some mixed tabs and spaces.

2017-07-26 22:50 UTC, mzlock commented on app/views/shared/partials/_header-global.html.erb
>  </header>
For the content, this is certainly one way to do the changing content per-page.  Lemme show you another way though:

```
<%= render "shared/partials/header-global", title: "You vs. The Machine", text: "Your text here..." %>
```
☝️ The variables that you add to the `render` line are then available in the rendered file, like so:

```
<header class="global-header">
  <h1><%= title %></h1>
  <p><%= text %></p>
</header>
```

2017-07-26 22:50 UTC, mzlock commented on app/views/roasts/index.html.erb
> +    </div>
Your indentation here should be 2 spaces, not 4

2017-07-26 22:50 UTC, mzlock commented on app/views/roasts/index.html.erb
> +    </div>
And this input needs a label.

```
<label class="screen-reader-only" for="roast-range">Roast Level: Light to Dark</label>
<input type="range" value="0" min="0" max="8" step="1" class="slider__range" id="roast-range">
```

☝️ note the `for` on the label and the `id` on the input

2017-07-26 22:50 UTC, mzlock commented on app/views/roasts/index.html.erb
> +        </section>
1. you're missing a closing `</div>` here

2. If you move lines 41-43 out of the brands loop, then you need to also move the closing tags for that HTML outside of the loop (after the `<% end %>` on the next line)

2017-07-26 23:03 UTC, ccomp commented on app/views/layouts/application.html.erb
> +<% url_path = request.fullpath.split("/") %>
Oops! I will delete that line.

2017-07-26 23:04 UTC, ccomp commented on app/views/roasts/index.html.erb
> +      <p><strong><%= roast.description %></strong></p>
It appears to be slightly more bold! There is a description and a sub_description, the latter which has more text.

2017-07-26 23:05 UTC, ccomp commented on app/views/roasts/index.html.erb
> +          <div class="brand__wrapper">
Oh you're right! I didn't see that.

2017-07-26 23:13 UTC, ccomp commented on app/views/roasts/index.html.erb
> +        </section>
Looks like I left in a redundant wrapper as well. Will fix that.

2017-07-26 23:16 UTC, ccomp commented on app/views/roasts/index.html.erb
> +    </div>
Gotcha, I'll make sure to add visibility:hidden to the "screen-reader-only" class as well.

2017-07-26 23:50 UTC, benjaminmodayil commented
👍  Megan already seemed to give you a good review for the base HTML and ERB integration.

2017-07-26 23:51 UTC, benjaminmodayil approved these changes

2017-08-01 14:32 UTC, jroodman commented
Didn't realize I was assigned to this - my b.

Same comments as on `Roasts page CSS and more!`

-SVG's likely need to be handled differently. Depending on the use case, lets talk.
-And some issues around your looping and use of Ruby code.

2017-08-02 16:21 UTC, closed without merging